# Generated by Django 4.2.7 on 2023-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INFST1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1', models.JSONField()),
                ('group2', models.JSONField()),
                ('group3', models.JSONField()),
                ('group4', models.JSONField()),
                ('group5', models.JSONField()),
                ('group6', models.JSONField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_speed', models.IntegerField(default=0)),
            ],
        ),
    ]
